### ISSUE TITLE
Firebasestorge Url does'not exist

### ISSUE THREAD

**Issue by Sabahsaeedi7** [bulgariamitko/flutterflowtutorials#3]
Hallo dimitri
I used this script but I got error for firebase Url storage ,I check the rul but everythings is right
could you help me

**Comment by bulgariamitko** [comment]
Yes that is a conman issue when you haven't setup your Firebase. You need to setup Firebase in your FF project and then setup a fake button to upload a document to FB in the page you want to use the code in order for FF to include the source code files. 

I will close this issue as this will fix the problem. IF you have anything else you want to update leave a command in this issue. 

Reference 
https://docs.flutterflow.io/data-and-backend/firebase/firebase-setup
https://docs.flutterflow.io/data-and-backend/firebase/firestore-database/storage-rules

**Comment by Sabahsaeedi7** [comment]
**### Thank you very much sir Dimitri**

**Comment by bulgariamitko** [comment]
@Sabahsaeedi7 , please provide the following details.
Which file from this repo you are using. 
Screenshots of the error
Your current setup

**Comment by Sabahsaeedi7** [comment]
Hallo Sir dimitri actually I use the file in packages. [flutterflowtutorials](https://github.com/bulgariamitko/flutterflowtutorials)/[Packages](https://github.com/bulgariamitko/flutterflowtutorials/tree/main/Packages)/pdf/

**Comment by Sabahsaeedi7** [comment]
[https://firebasestorage.googleapis.com/v0/b/bsms-dc252.appspot.com/o/pdfs%2FScreenshot%202023-04-29%20at%2014.54.26.png?alt=media&token=9dc4815e-d1dd-412a-b911-469a66915787](url)

[https://firebasestorage.googleapis.com/v0/b/bsms-dc252.appspot.com/o/pdfs%2FScreenshot%202023-04-29%20at%2014.54.14.png?alt=media&token=ee69dd0c-3b94-46de-a289-ab0268232731](url)

**Comment by bulgariamitko** [comment]
@Sabahsaeedi7 the files that you share cant be open

**Comment by Sabahsaeedi7** [comment]
![Screenshot 2023-04-29 at 14 54 14](https://user-images.githubusercontent.com/102438620/235316784-dc95709a-b7d5-4cd3-9825-43383743ba1d.png)
![Screenshot 2023-04-29 at 14 54 26](https://user-images.githubusercontent.com/102438620/235316788-e6011e2d-4ef3-4da7-b420-5e17daa68da9.png)

**Comment by Sabahsaeedi7** [comment]
Im so sorry sir I sent it again

**Comment by bulgariamitko** [comment]
@Sabahsaeedi7 , did you check the check on the right side "Exclude from compilation"? This has to be checked and then try again.

**Comment by Sabahsaeedi7** [comment]
THANK YOUR VERY MACH bro ,I did it but during the running wan not working and got some error in broweser

**Comment by Sabahsaeedi7** [comment]
Ok it running succefulluy but when we push the button face to this error in browser
rt_sdk.js:5397 Uncaught (in promise) Error: RangeError (index): Index out of range: no indices are valid: 0
    at Object.throw_ [as throw] (dart_sdk.js:5397:11)
    at Object._checkValidIndex (dart_sdk.js:33641:17)
    at [dartx._get] (dart_sdk.js:32806:26)
    at input_buffer.InputBuffer.new._get (input_buffer.dart:44:39)
    at jpeg_data.JpegData.new.validate (jpeg_data.dart:64:17)
    at jpeg_decoder.JpegDecoder.new.isValidFile (jpeg_decoder.dart:18:50)
    at Object.findDecoderForData (formats.dart:116:10)
    at MemoryImage.new (image_provider.dart:101:24)
    at pdfInvoiceDownload (pdf_invoice_download.dart:37:20)
    at pdfInvoiceDownload.next (<anonymous>)
    at dart_sdk.js:40691:33
    at _RootZone.runUnary (dart_sdk.js:40524:59)
    at _FutureListener.thenAwait.handleValue (dart_sdk.js:35738:29)
    at handleValueCallback (dart_sdk.js:36299:49)
    at _Future._propagateToListeners (dart_sdk.js:36337:17)
    at [_completeWithValue] (dart_sdk.js:36172:23)
    at async._AsyncCallbackEntry.new.callback (dart_sdk.js:36206:35)
    at Object._microtaskLoop (dart_sdk.js:40821:13)
    at _startMicrotaskLoop (dart_sdk.js:40827:13)
    at dart_sdk.js:36561:9
t

**Comment by Sabahsaeedi7** [comment]
in the end I got error with assets.  rt_sdk.js:62768 Error while trying to load an asset: Failed to load asset at "assets//assets/fonts/Lateef-Bold.ttf" (404)



dart_sdk.js:5397 Uncaught (in promise) Error: Unable to load asset: "/assets/fonts/Lateef-Bold.ttf".
The asset does not exist or has empty data.
    at Object.throw_ [as throw] (dart_sdk.js:5397:11)
 please help me

**Comment by Sabahsaeedi7** [comment]
and this is pubspec file without font path

name: saloon
description: A new Flutter project.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: 3.0.0
  built_collection: 5.1.1
  built_value: 8.4.3
  cached_network_image: 3.2.1
  cloud_firestore: 4.2.0
  cloud_firestore_platform_interface: 5.9.1
  cloud_firestore_web: 3.1.1
  data_table_2: 2.3.12
  dropdown_button2: 2.0.0
  easy_debounce: 2.0.1
  file_picker: 5.2.6
  firebase_auth: 4.2.0
  firebase_auth_platform_interface: 6.11.4
  firebase_auth_web: 5.2.0
  firebase_core: 2.4.0
  firebase_core_platform_interface: 4.5.2
  firebase_core_web: 2.0.2
  firebase_storage: 11.0.7
  firebase_storage_platform_interface: 4.1.25
  firebase_storage_web: 3.3.17
  flutter_animate: 4.1.1+1
  flutter_cache_manager: 3.3.0
  flutter_plugin_android_lifecycle: 2.0.9
  flutter_spinkit: 5.1.0
  font_awesome_flutter: 10.1.0
  from_css_color: 2.0.0
  google_fonts: 4.0.3
  google_sign_in: 5.4.0
  google_sign_in_android: 6.1.8
  google_sign_in_ios: 5.4.0
  google_sign_in_platform_interface: 2.2.0
  google_sign_in_web: 0.10.2
  image_picker: 0.8.5+3
  image_picker_android: 0.8.5+3
  image_picker_for_web: 2.1.10
  image_picker_ios: 0.8.6+1
  image_picker_platform_interface: 2.6.2
  intl: 0.17.0
  json_path: 0.4.1
  json_serializable: 6.6.1
  mime_type: 1.0.0
  octo_image: 1.0.2
  page_transition: 2.0.4
  path_provider: 2.0.14
  path_provider_android: 2.0.25
  path_provider_foundation: 2.2.2
  path_provider_platform_interface: 2.0.6
  plugin_platform_interface: 2.1.3
  provider: 6.0.4
  rxdart: 0.27.5
  shared_preferences: 2.0.15
  shared_preferences_android: 2.1.0
  shared_preferences_ios: 2.1.1
  shared_preferences_platform_interface: 2.2.0
  shared_preferences_web: 2.1.0
  sign_in_with_apple: 4.1.0
  sign_in_with_apple_platform_interface: 1.0.0
  sign_in_with_apple_web: 1.0.1
  simple_gradient_text: 1.2.3
  sqflite: 2.2.6
  styled_divider: 1.0.4
  timeago: 3.2.2
  url_launcher: 6.1.10
  url_launcher_android: 6.0.27
  url_launcher_ios: 6.1.4
  url_launcher_platform_interface: 2.1.2
  video_player: 2.6.0
  video_player_android: 2.4.3
  video_player_avfoundation: 2.4.2
  video_player_platform_interface: 6.1.0
  video_player_web: 2.0.15


dev_dependencies:
  analyzer: 5.10.0
  build_runner: 2.3.3
  built_value_generator: 8.4.3

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/

**Comment by bulgariamitko** [comment]
About the asset you need to run the code using Web Deployment, because running it with assets in Test/Run mode will not work.

**Comment by bulgariamitko** [comment]
I will close this issue as you are not active for more then 3 days if you still facing the same error please write in this issue and I will reopen it.
